// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://osyzrndwrjblctoziikd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9zeXpybmR3cmpibGN0b3ppaWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNTI2ODYsImV4cCI6MjA2OTcyODY4Nn0.GLju7ZaXJDMNOZZppe8_ZrD3O2wTluDm6JGMq-xKoA8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});